# IFRS to GAAP Concept Mapping
# Maps IFRS concepts to US GAAP equivalents for cross-jurisdiction analysis

Revenue:
  prefer: 
    - ifrs:Revenue
    - ifrs-full:Revenue
  fallback_gaap: 
    - us-gaap:Revenues
    - us-gaap:SalesRevenueNet

CostOfSales:
  prefer: 
    - ifrs:CostOfSales
  fallback_gaap: 
    - us-gaap:CostOfGoodsAndServicesSold

OperatingIncome:
  prefer: 
    - ifrs:ProfitLossFromOperatingActivities
  fallback_gaap: 
    - us-gaap:OperatingIncomeLoss

NetIncome:
  prefer: 
    - ifrs:ProfitLoss
  fallback_gaap: 
    - us-gaap:NetIncomeLoss

Assets:
  prefer: 
    - ifrs:Assets
  fallback_gaap: 
    - us-gaap:Assets

Equity:
  prefer: 
    - ifrs:Equity
  fallback_gaap: 
    - us-gaap:StockholdersEquity

CashFromOperations:
  prefer: 
    - ifrs:NetCashFlowsFromUsedInOperatingActivities
  fallback_gaap: 
    - us-gaap:NetCashProvidedByUsedInOperatingActivities

CurrentAssets:
  prefer: 
    - ifrs:CurrentAssets
  fallback_gaap: 
    - us-gaap:AssetsCurrent

CurrentLiabilities:
  prefer: 
    - ifrs:CurrentLiabilities
  fallback_gaap: 
    - us-gaap:LiabilitiesCurrent

SharesDiluted:
  prefer: 
    - ifrs:WeightedAverageNumberOfSharesOutstandingDiluted
  fallback_gaap: 
    - us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding

DepreciationAndAmortization:
  prefer:
    - ifrs:DepreciationAndAmortisation
    - ifrs:DepreciationDepletionAndAmortisation
  fallback_gaap:
    - us-gaap:DepreciationDepletionAndAmortization

CashFromInvesting:
  prefer:
    - ifrs:NetCashFlowsFromUsedInInvestingActivities
  fallback_gaap:
    - us-gaap:NetCashProvidedByUsedInInvestingActivities

CashFromFinancing:
  prefer:
    - ifrs:NetCashFlowsFromUsedInFinancingActivities
  fallback_gaap:
    - us-gaap:NetCashProvidedByUsedInFinancingActivities

TotalDebt:
  prefer:
    - ifrs:FinancialLiabilities
    - ifrs:LoansAndBorrowings
  fallback_gaap:
    - us-gaap:DebtLongtermAndShorttermCombinedAmount
    - us-gaap:LongTermDebt

CashAndEquivalents:
  prefer:
    - ifrs:CashAndCashEquivalents
  fallback_gaap:
    - us-gaap:CashAndCashEquivalentsAtCarryingValue
    - us-gaap:CashCashEquivalentsAndShortTermInvestments

InterestExpense:
  prefer:
    - ifrs:InterestExpense
  fallback_gaap:
    - us-gaap:InterestExpense
