# FinSight Data Sources Registry v1.0
# Regulator-first, multi-source finance data with provenance tracking

# U.S. Tier-1 Sources (Day One)
- id: sec_submissions
  jurisdiction: US
  type: filings_index
  authority: SEC
  status: ready
  base_url: https://data.sec.gov/submissions/
  endpoints:
    company_submissions: "{cik_padded}.json"
  auth: none
  etiquette: 
    user_agent_required: true
    rpm_soft: 10
    backoff_on: [403, 429]
  output: company_filings_index
  notes: "Use descriptive User-Agent; backoff on 403/429; pad CIK to 10 digits"

- id: sec_companyfacts
  jurisdiction: US
  type: xbrl_company_facts
  authority: SEC
  status: ready
  base_url: https://data.sec.gov/api/xbrl/companyfacts/
  endpoints:
    facts: "CIK{cik_padded}.json"
  auth: none
  etiquette:
    user_agent_required: true
    rpm_soft: 10
    backoff_on: [403, 429]
  output: xbrl_company_facts
  notes: "Canonical XBRL facts by company with full history and dimensions"

- id: sec_frames
  jurisdiction: US
  type: xbrl_frames
  authority: SEC
  status: ready
  base_url: https://data.sec.gov/api/xbrl/frames/
  endpoints:
    frame: "{taxonomy}/{concept}/{unit}/{period}.json"
  auth: none
  etiquette:
    user_agent_required: true
    rpm_soft: 10
    backoff_on: [403, 429]
  output: xbrl_frames
  notes: "Cross-company XBRL frames for benchmarking (e.g., us-gaap/Assets/USD/CY2024Q4I.json)"

- id: fred
  jurisdiction: US
  type: macro
  authority: Federal Reserve
  status: ready
  base_url: https://api.stlouisfed.org/fred/
  endpoints:
    series: "series/observations?series_id={id}&api_key={key}&file_type=json"
    metadata: "series?series_id={id}&api_key={key}&file_type=json"
  auth: api_key_optional
  etiquette:
    rpm_soft: 120
  output: macro_series
  notes: "One API for thousands of macro series (CPI, GDP, yields, etc.)"

- id: bls
  jurisdiction: US
  type: macro
  authority: BLS
  status: ready
  base_url: https://api.bls.gov/publicAPI/v2/
  endpoints:
    timeseries: "timeseries/data/"
  auth: api_key_optional
  etiquette:
    rpm_soft: 500
  output: macro_series
  notes: "Official CPI, PPI, employment data from Bureau of Labor Statistics"

- id: bea
  jurisdiction: US
  type: macro
  authority: BEA
  status: ready
  base_url: https://apps.bea.gov/api/data/
  endpoints:
    nipa: "?UserID={key}&method=GetData&DataSetName=NIPA&TableName={table}&Year={year}&Frequency={freq}"
    gdp: "?UserID={key}&method=GetData&DataSetName=NIPA&TableName=T10101&Year={year}"
  auth: api_key_required
  etiquette:
    rpm_soft: 1000
  output: macro_series
  notes: "NIPA tables, GDP, personal income from Bureau of Economic Analysis"

- id: treasury_h15
  jurisdiction: US
  type: rates
  authority: U.S. Treasury
  status: ready
  base_url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/avg_interest_rates/
  endpoints:
    yields: "?"
  auth: none
  etiquette:
    rpm_soft: 1000
  output: macro_series
  notes: "Daily Treasury par yield curve and related rates"

- id: eia
  jurisdiction: US
  type: energy
  authority: EIA
  status: ready
  base_url: https://api.eia.gov/series/
  endpoints:
    series: "?api_key={key}&series_id={id}"
  auth: api_key_required
  etiquette:
    rpm_soft: 500
  output: macro_series
  notes: "Energy data (WTI inventories, electricity, etc.) from Energy Information Administration"

- id: worldbank
  jurisdiction: global
  type: macro
  authority: World Bank
  status: ready
  base_url: https://api.worldbank.org/v2/
  endpoints:
    indicator: "country/{country}/indicator/{indicator}?format=json"
    metadata: "country/{country}?format=json"
  auth: none
  etiquette:
    rpm_soft: 1000
  output: macro_series
  notes: "Global macro indicators with consistent country codes and metadata"

# Non-U.S. Sources (Wave 2 - Planned)
- id: jp_edinet
  jurisdiction: JP
  type: filings_index
  authority: FSA
  status: planned
  base_url: https://disclosure.edinet-fsa.go.jp/api/v2/
  endpoints:
    search: "documents.json"
    download: "documents/{doc_id}"
  auth: none
  etiquette:
    rpm_soft: 60
  output: filings_documents
  notes: "Japan EDINET API for annual/semi-annual/Q reports with proper JSON schema"

- id: kr_dart
  jurisdiction: KR
  type: filings_index
  authority: FSS
  status: planned
  base_url: https://opendart.fss.or.kr/api/
  endpoints:
    list: "list.json"
    doc: "document.xml"
  auth: api_key_required
  etiquette:
    rpm_soft: 100
  output: filings_documents
  notes: "Korea DART API for timely disclosures with good JSON schema"

- id: uk_nsm
  jurisdiction: UK
  type: regulatory_news
  authority: FCA
  status: planned
  base_url: https://data.fca.org.uk/
  endpoints:
    rns: "nsm/rns"
  auth: none
  etiquette:
    rpm_soft: 30
  output: filings_documents
  notes: "UK FCA National Storage Mechanism for regulatory news (RNS) - HTML/PDF routing"

- id: eu_oam
  jurisdiction: EU
  type: filings_index
  authority: ESMA/OAMs
  status: planned
  base_url: https://ec.europa.eu/info/business-economy-euro/company-reporting-and-auditing/company-reporting/electronic-reporting/ese-filing-requirements_en
  endpoints:
    country_specific: "varies by country"
  auth: none
  etiquette:
    rpm_soft: 30
  output: filings_documents
  notes: "EU ESEF XHTML filings via country-specific OAMs (DE, FR, etc.) - wave deployment"

- id: hk_hkex
  jurisdiction: HK
  type: filings_index
  authority: HKEX
  status: planned
  base_url: https://www.hkexnews.hk/
  endpoints:
    search: "search/"
  auth: none
  etiquette:
    rpm_soft: 30
  output: filings_documents
  notes: "HKEX news for timely disclosure PDFs/XHTML - treat cautiously, front-end JSON not formally documented"

# Identifier Mapping Services
- id: openfigi
  jurisdiction: global
  type: identifier_mapping
  authority: Bloomberg
  status: ready
  base_url: https://api.openfigi.com/v3/
  endpoints:
    mapping: "mapping"
  auth: none
  etiquette:
    rpm_soft: 100
  output: identifier_mapping
  notes: "Free FIGI mapping service for ISIN/CUSIP/ticker ↔ FIGI conversions"

- id: sec_cik_mapping
  jurisdiction: US
  type: identifier_mapping
  authority: SEC
  status: ready
  base_url: https://www.sec.gov/files/company_tickers.json
  endpoints:
    tickers: ""
  auth: none
  etiquette:
    rpm_soft: 1000
  output: identifier_mapping
  notes: "SEC ticker ↔ CIK mapping for US companies"

# ECB FX Rates
- id: ecb_sdw_fx
  jurisdiction: EU
  type: fx
  authority: ECB
  status: ready
  base_url: https://data-api.ecb.europa.eu/service/data/
  endpoints:
    series: "EXR/D.{BASE}.{QUOTE}.SP00.A?lastNObservations={n}&format=csvdata"
  auth: none
  etiquette:
    rpm_soft: 5
  output: fx_series
  notes: "Daily ECB reference rates (CSV). Use Accept: text/csv, fallback JSON if needed."

